cmake_minimum_required(VERSION 3.30)
project(Projeto)

set(CMAKE_CXX_STANDARD 20)

add_executable(Projeto
        main.cpp
        Entidades/Planta/Cacto/cacto.cpp
        Entidades/Ferramenta/ferramenta.cpp
        Entidades/Jardineiro/jardineiro.cpp
        Entidades/Planta/planta.cpp
        Entidades/Ferramenta/Regador/regador.cpp
        Entidades/Planta/Roseira/roseira.cpp
        Comandos/comandos.cpp
        Jardim/jardim.cpp
        Jardim/jardim.h
        Solo/solo.cpp
        utilidades.h
        utilidades.cpp
        Entidades/Planta/ErvaDaninha/erva.cpp
        Entidades/Planta/ErvaDaninha/erva.h
        Entidades/Ferramenta/PacoteAdubo/adubo.cpp
        Entidades/Ferramenta/PacoteAdubo/adubo.h
        Entidades/Ferramenta/TesouraPoda/tesoura.cpp
        Entidades/Ferramenta/TesouraPoda/tesoura.h
        Entidades/Ferramenta/EnxadaRotativa/enxadarotativa.cpp
        Entidades/Ferramenta/EnxadaRotativa/enxadarotativa.h
        Gestor/gestorcmd.cpp
        Gestor/gestorcmd.h
        Comandos/Ajuda/Ajuda.cpp
        Comandos/Ajuda/Ajuda.h
        Comandos/Avanca/avanca.cpp
        Comandos/Avanca/avanca.h
        Comandos/Planta/planta.cpp
        Comandos/Planta/planta.h
        Entidades/Planta/PlantaExotica/sentinela.cpp
        Entidades/Planta/PlantaExotica/sentinela.h
        Comandos/Lplanta/lplanta.cpp
        Comandos/Lplanta/lplanta.h
        Comandos/Larea/larea.cpp
        Comandos/Larea/larea.h
        Comandos/Lsolo/lsolo.cpp
        Comandos/Lsolo/lsolo.h
        Comandos/Lferr/lferr.cpp
        Comandos/Lferr/lferr.h
        Comandos/Lplantas/lplantas.cpp
        Comandos/Lplantas/lplantas.h
        Comandos/Colhe/colhe.cpp
        Comandos/Colhe/colhe.h
        Comandos/Larga/larga.cpp
        Comandos/Larga/larga.h
        Comandos/Compra/compra.cpp
        Comandos/Compra/compra.h
        Comandos/Pega/pega.cpp
        Comandos/Pega/pega.h
        Comandos/Movimentos/movimentos.cpp
        Comandos/Movimentos/movimentos.h
        Comandos/Entra/entra.cpp
        Comandos/Entra/entra.h
        Comandos/Sai/sai.cpp
        Comandos/Sai/sai.h
        Comandos/Jardim/jardim.cpp
        Comandos/Jardim/jardim.h
        Comandos/Grava/grava.cpp
        Comandos/Grava/grava.h
        Comandos/Recupera/recupera.cpp
        Comandos/Recupera/recupera.h
        Comandos/Apaga/apaga.cpp
        Comandos/Apaga/apaga.h
        Comandos/Executa/executa.cpp
        Comandos/Executa/executa.h
        Comandos/Fim/fim.cpp
        Comandos/Fim/fim.h
        Backup/Backup.cpp
        Backup/Backup.h
)
